---
title: 'Problem Set 3: Instrumental Variables Key'
author: "Claire Duquennois"
output:
  pdf_document:
    number_sections: true
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***Name:***


# Empirical Analysis using Data from Ananat (2011, AEJ:AE)


This exercise uses data from Elizabeth Ananat's paper, "The Wrong Side(s) of the Tracks: The Causal Effects of Racial Segregation on Urban Poverty and Inequality," published in the *American Economic Journal: Applied Economics* in 2011. This paper studies how segregation has affected population characteristics and income disparity in US cities using the layout of railroad tracks as an instrumental variable. 


# Finding the data

The data can be found by following the link on the AEJ: Applied Economics' website which will take you to the ICPSR's data repository. You will need to sign in to get access to the data files. Once logged in, you will find the set of files that are typically included in a replication file. These include several datasets, several .do files (which is a STATA command file). For this assignment we will be using the`aej_maindata.dta` file.

 \clearpage


# Set up and opening the data

## Question: Load any packages you will need and the data contained in the `aej_maindata.dta` file. How many observations are contained in the data. What is the level of an observation? 

**Code and Answer:**



 \clearpage
 
# Data Description

## Question:The dataset contains many variables, some of which are not used in this exercise. Keep the following variables in the final dataset (Hint: use the `select` function in `dplyr`). 

| Name     |Description                                                             |
|----------|------------------------------------------------------------------------|
|dism1990	 |1990 dissimilarity index                                                | 
|herf      |RDI (Railroad division index)                                           |
|lenper    |Track length per square km                                              |
|povrate_w |White poverty rate 1990                                                 |
|povrate_b |Black poverty rate 1990                                                 |
|area1910  |Physical area in 1910 (1000 sq. miles)                                  |
|count1910 |Population in 1910 (1000s)                                              | 
|ethseg10  |Ethnic Dissimilariy index in 1910                                       |
|ethiso10  |Ethnic isolation index in 1910                                          |
|black1910 |Percent Black in 1910                                                   |
|passpc    |Street cars per capita 1915                                             |
|black1920 |Percent Black 1920                                                      |
|lfp1920   |Labor Force Participation 1920                                          |
|incseg    |Income segregation 1990                                                 |
|pctbk1990 |Percent Black 1990                                                      |
|manshr    |Share employed in manufacturing 1990                                    |
|pop1990   |Population in 1990                                                      |

**You can find the detailed description of each variable in the original paper. **

**Code:**


 \clearpage

# Summary Statistics: 


## Question: Report summary statistics of the following variables in the dataset:"dism1990", "herf", "lenper", "povrate_w", "povrate_b". Present these summary statistics in a formatted table, you can use `stargazer` or other packages.

**Code:**


 \clearpage

# Reduced Form:

## Question: We are interested in understanding how segregation affects population characteristics and income disparity in US cities. We will focus on two outcome variables: the poverty rate for blacks and whites. Regress these two outcome variables on segregation in 1990, our explanatory variable, and interpret your results. Report robust standard errors. Make sure you specify the units of measurement in your interpretation. 

**Code:**

**Answer:**

 \clearpage


## Question: Explain the problem with giving a causal interpretation to the estimates you just produced. Give examples of specific factors that might make a causal interpretation of your result problematic.

**Answer:**

 \clearpage

# Validity of the instrument:

## Question: Estimate the following regression and interpret it's coefficients, 
$$
 dism1990_i=\beta_0+\beta_1RDI_i+\beta_2 tracklength_i+\epsilon.
$$

**Code:**

**Answer:**

 \clearpage

## Question: Re-estimate the specification above using the `scale()` command around the variables you wish to standardize in the regression. What do you notice?

**Code:**


**Answer:**


 \clearpage


## Question: In the context of instrumental variables, what is this regression referred to as and why is it important? 

**Answer:**

\clearpage

## Question: Illustrate the relationship between the RDI and segregation graphically. 

**Code:**

 \clearpage

## Question: Is there a concern that this might be a weak instrument? Why would this be a problem?

**Answer:**



 \clearpage


## Question: Select a number of relevant city characteristics in the data to regress on the RDI and track length. Present your results and interpret your findings. Why do these results matter for answering our question of interest? 

**Code and Answer:**

 \clearpage


## Question: What are the two conditions necessary for a valid instrument? What evidence do you have that the RDI meet these conditions? Be specific in supporting this claim. 

**Answer:**

 \clearpage

## Question: Do you believe the instrument is valid? Why/why not?

**Answer:**

 \clearpage

## Question: Generate a table that estimates the effect of segregation on the poverty rate for blacks and whites by OLS and then using the RDI instrument. Make sure you report robust standard errors. How does the use of the RDI instrument change the estimated coefficients? 

**Code and Answer:**

 \clearpage

## Question: What is the reduced form equation?

**Answer:**



 \clearpage

## Question: (2 pages) For the two poverty rates, estimate the reduced form on all the cities and illustrate the reduced form relationships graphically.

**Code:**


 \clearpage

## Question: Generate a table with at least six estimations that checks whether the main results are robust to adding additional controls for city characteristics. What do you conclude?

**Code:**

**Answer:**

 \clearpage


# Why **Two Stage** least squares? 

Because the estimates in this paper only feature one endogenous regressor and one instrument, it is an excellent example with which to illustrate build intuition and see what the instrumental variables regressor is actually doing because in this scenario the IV estimator is exactly equal to the two stage least squares estimator ($\hat{\beta}_{IV}=\hat{\beta}_{2SLS}$).


## Question: Estimate the first stage regression and use your estimates to generate the predicted values for the explanatory variable for all the observations.

**Code:**

 \clearpage

## Question: If our instrument is valid, the step above "removed" the "bad" endogenous variation from the predicted explanatory variable, keeping only the exogenous variation that is generated by the instrument. Now run the second stage by regressing our outcome variable on the predicted values generated above and the relevant controls. Compare your estimates from this regression to those generated earlier. How do they compare?

**Code:**


**Answer:**

 \clearpage

# Yet another IV trick: Taking the "Good" variation and scaling it

## Question: Take the coefficient from you reduced form estimate and divide it by your first stage estimate. How does this value compare your earlier estimate for the main result? 

**Answer:**




# Submission instructions:

- Make sure the final version of your assignment is knit in pdf format and uploaded to gradescope. Make sure you have one question response per page (unless otherwise indicated) so that question positions align with the template in gradescope.The final PDF should be 22 pages long. 



